Algoritmo "Exercicio 3 Repetição"
//Luan Zuchinali Zanardo Turma: 1137
Var

nome : caracter
media : real
contador : inteiro

Inicio

para contador de 1 ate 5 faca
escreva("Digite nome do  aluno: ")
leia(nome)
escreva("Digite media do aluno: ")
leia(media)
se (media >= 7) entao
escreva("Aluno esta aprovado!!")
fimse
se (media < 7) entao
escreva("Aluno esta reprovado!!")
fimse
fimpara

Fimalgoritmo