Algoritmo "Exercicio 2 Repetição"
//Luan Zuchinali Zanardo Turma: 1137
Var

nome : caracter
cidade : caracter
estado : caracter
telefone : inteiro
contador : inteiro

Inicio

para contador de 1 ate 5 faca
escreva("Digite nome: ")
leia(nome)
escreva("Digite sua cidade: ")
leia(cidade)
escreva("Digite seu estado: ")
leia(estado)
escreva("Digite seu telefone: ")
leia(telefone)
fimpara

Fimalgoritmo