Algoritmo "Estrutura de seleção 08"
//Luan Zuchinali Zanardo Turma 1137

Var

estado : caracter

Inicio

escreva("Digite a sigla do seu estado de nascimento: ")
escreva("RS")
escreva("SC")
escreva("PR")
leia(estado)

se (estado = "RS")entao
escreva("Você nasceu em Rio Grande do Sul")
fimse

se (estado = "SC")entao
escreva("Você nasceu em Santa Catarina")
fimse

se (estado = "PR")entao
escreva("Você nasceu em Parana")
fimse

Fimalgoritmo