Algoritmo "Estrutura de seleção 06"
//Luan Zuchinali Zanardo Turma 1137

Var

EstadoCivil : caracter

Inicio

escreval("Informe seu estado civil: ")
escreval("S - Solteiro")
escreval("C - Casado")
escreval("V - Viúvo")
escreval("D - Divorciado")
leia(EstadoCivil)

escolha (EstadoCivil)
caso "S"
escreva("Você é Solteiro")
caso "C"
escreva("Você é Casado")
caso "V"
escreva("Você é Viúvo")
caso "D"
escreva("Você é Divorciado")
fimescolha
Fimalgoritmo