Algoritmo "Script 08"
//Luan Zanardo Turma 1137

Var

nome : caracter
idade : inteiro
altura : real
peso : real
massa : real

Inicio

escreva("Digite seu nome: ")
leia(nome)
escreva("Digite sua idade: ")
leia(idade)
escreva("Digite sua altura: ")
leia(altura)
escreva("Digite seu peso: ")
leia(peso)
massa := peso / (altura * altura)
escreva("IMC do atleta: ", massa)
Fimalgoritmo